version: 2

run:
  timeout: 10m
  concurrency: 2
  modules-download-mode: readonly

output:
  # Satisfies "order the results by file"
  sort-order:
    - file
    - linter

linters:
  default: all
  disable:
    # --- Style & Idiom (Too Opinionated) ---
    - wsl             # Too strict; conflicts with logical grouping.

    # --- Style Preference ---
    - noinlineerr     # Disabled to allow idiomatic `if err :=...`
    - err113
    - errcheck
    - exhaustruct
    - funlen
    - gochecknoinits
    - gocognit
    - gosec
    - lll
    - mnd
    - nestif
    - revive
    - varnamelen
    - cyclop
    - gochecknoglobals
    - unparam
    - wrapcheck
    - depguard

  exclusions:
    generated: strict
    warn-unused: true
    presets:
      # - comments
      # - std-error-handling
      # - common-false-positives
      # - legacy
    rules:
      - path: "cmd/version/version.go"
        linters:
          - gochecknoinits
          - exhaustruct
          - gochecknoglobals
          - errcheck

  settings:
    gofumpt:
      extra-rules: true

    depguard:
      rules:
        # Rule 1: Production Code (Main)
        main:
          list-mode: strict
          files:
            - "$all"
            - "!$test" # Critical: Exclude test files from this strict rule
          allow:
            - $gostd
            # Allow SDKs
            - golang.org/x/oauth2
            - github.com/spf13/cobra
            - google.golang.org/grpc
            - github.com/charmbracelet/huh
            - gopkg.in/yaml.v3
            - github.com/denormal/go-gitignore
            - github.com/shurcooL/githubv4
            - github.com/google/go-github/v74/github
            - github.com/fatih/color
            - github.com/mattn/go-isatty
            # Allow your project imports
            - github.com/contextvibes/cli
            - github.com/mark3labs/mcp-go/mcp
          deny:
            - pkg: "math/rand$"
              desc: "Use math/rand/v2 for safer, faster generation (Go 1.22+)"
            - pkg: "github.com/pkg/errors"
              desc: "Use stdlib errors.New, fmt.Errorf, and errors.Is/As"
            - pkg: "github.com/sirupsen/logrus"
              desc: "Use log/slog (stdlib) or uber-go/zap"

    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        # --- Architecture Exemptions (Dependency Injection) ---
        - github.com/contextvibes/cli/internal/workitem.Provider
        - github.com/contextvibes/cli/internal/exec.CommandExecutor
        - github.com/contextvibes/cli/internal/workflow.PresenterInterface

    gosec:
      excludes:
        - G101 # Exclude "Hardcoded Credentials" (false positives with IaC resource names)

    errorlint:
      errorf: true
      asserts: true

    testifylint:
      enable-all: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - vendor
