version: 2

run:
  timeout: 10m
  concurrency: 2
  modules-download-mode: readonly

linters:
  # 1. Enable EVERY available linter
  default: all

  # 2. Disable specific linters.
  disable:
    # --- DEPRECATED / REMOVED LINTERS ---
    - wsl

    # --- LEVEL 1: CRITICAL BUGS & SECURITY ---
    # - forcetypeassert
    # - gosec

    # --- LEVEL 2: STYLE & MODERNIZATION ---
    # - modernize
    # - perfsprint
    # - revive
    # - unused
    # - goconst

    # --- LEVEL 3: ERROR HANDLING & BEST PRACTICES ---
    # - err113
    # - nilerr
    # - nlreturn
    # - noinlineerr
    # - staticcheck
    # - errcheck          # Unchecked errors
    # - nonamedreturns    # Named returns usage

    # --- LEVEL 4: COMPLEXITY & REFACTORING ---
    # - cyclop
    # - funlen
    # - gocognit
    # - maintidx
    # - mnd
    # - nestif
    # - wrapcheck

    # --- LEVEL 5: STRICT STANDARDS & OPINIONS ---
    # - depguard
    # - exhaustruct
    # - gochecknoglobals
    # - godoclint
    # - ireturn
    # - lll
    # - varnamelen
    # - wsl_v5
    # - forbidigo         # Forbidden identifiers (fmt.Print, etc)
    # - funcorder         # Function ordering
    # - gochecknoinits    # Init functions
    # - godox             # TODOs
    # - goprintffuncname  # Printf-like naming
    # - tagliatelle       # JSON struct tags
    - nolintlint

    # --- TESTING ---
    # - testifylint
    # - usetesting
    # - paralleltest      # (Added to ensure tests run without forcing parallel)

    # --- NOISE / LOW VALUE ---
    # - gocritic
    # - thelper
    # - unparam
    # - exhaustive        # Exhaustive switch statements

  settings:
    ireturn:
      allow:
        - error
    depguard:
      rules:
        main:
          list-mode: lax
          files:
            - "!**/*_a _file.go"
          allow:
            - $gostd
            - github.com/OpenPeeDeeP
          deny:
            - pkg: "math/rand$"
              desc: use math/rand/v2
            - pkg: "github.com/sirupsen/logrus"
              desc: not allowed
            - pkg: "github.com/pkg/errors"
              desc: Should be replaced by standard lib errors package
