version: 2

run:
  timeout: 10m
  concurrency: 2
  modules-download-mode: readonly

output:
  sort-order:
    - file
    - linter

linters:
  default: all
  disable:
    - wsl
    - noinlineerr
    - err113
    - errcheck
    - funlen
    - gochecknoinits
    - gocognit
    - gosec
    - lll
    - mnd
    - nestif
    - revive
    - varnamelen
    - cyclop
    # - gochecknoglobals
    - unparam
    - wrapcheck
    - depguard
    # We keep exhaustruct disabled in the general list for now to avoid noise in other files,
    # but we configure the settings below so that IF enabled (e.g. via strict mode), it behaves correctly.

  exclusions:
      generated: strict
      warn-unused: true
      presets:
        # - comments
        # - std-error-handling
        # - common-false-positives
        # - legacy
      rules:
        # Allow globals for build-time variables and embedded descriptions
        - path: "cmd/(version/version|feedback/feedback)\\.go$"
          linters:
            - gochecknoglobals

        # Allow globals for build-time injection
        - path: "internal/build/build\\.go$"
          linters:
            - gochecknoglobals

        # Allow globals for the "Bridge Pattern" in tests
        # Regex explanation: Matches any file ending in "export_test.go"
        - path: "export_test\\.go$"
          linters:
            - gochecknoglobals
            - exhaustruct


  settings:
    gofumpt:
      extra-rules: true

    # --- NEW CONFIGURATION ---
    exhaustruct:
      exclude:
        # Exclude Cobra commands as per research findings (Fragile Structs)
        - "^github.com/spf13/cobra.Command$"

    depguard:
      rules:
        main:
          list-mode: strict
          files:
            - "$all"
            - "!$test"
          allow:
            - $gostd
            - golang.org/x/oauth2
            - github.com/spf13/cobra
            - google.golang.org/grpc
            - github.com/charmbracelet/huh
            - gopkg.in/yaml.v3
            - github.com/denormal/go-gitignore
            - github.com/shurcooL/githubv4
            - github.com/google/go-github/v74/github
            - github.com/fatih/color
            - github.com/mattn/go-isatty
            - github.com/contextvibes/cli
            - github.com/mark3labs/mcp-go/mcp
          deny:
            - pkg: "math/rand$"
              desc: "Use math/rand/v2 for safer, faster generation (Go 1.22+)"
            - pkg: "github.com/pkg/errors"
              desc: "Use stdlib errors.New, fmt.Errorf, and errors.Is/As"
            - pkg: "github.com/sirupsen/logrus"
              desc: "Use log/slog (stdlib) or uber-go/zap"

    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - github.com/contextvibes/cli/internal/workitem.Provider
        - github.com/contextvibes/cli/internal/exec.CommandExecutor
        - github.com/contextvibes/cli/internal/workflow.PresenterInterface

    gosec:
      excludes:
        - G101

    errorlint:
      errorf: true
      asserts: true

    testifylint:
      enable-all: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-dirs:
    - vendor
